#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'pihole'
        intport: '53/tcp'
        extport: '53'
        intport2: '53/udp'
        extport2: '53'
        intport3: '80'
        extport3: '8182'
        intport4: '443'
        extport4: '8183'
        image: 'pihole/pihole:latest'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/coreapps/apps/_core.yml'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
           traefik.enable: 'true'
           traefik.backend: '{{pgrole}}'
           traefik.frontend.rule: 'HostRegexp:{{pgrole}}.{{domain.stdout}},{{tldset}},{catchall:.*}'
           traefik.frontend.priority: '1'
           traefik.frontend.headers.SSLRedirect: 'true'
           traefik.frontend.headers.STSSeconds: '315360000'
           traefik.frontend.headers.browserXSSFilter: 'true'
           traefik.frontend.headers.contentTypeNosniff: 'true'
           traefik.frontend.headers.forceSTSHeader: 'true'
           traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
           traefik.frontend.headers.STSIncludeSubdomains: 'true'
           traefik.frontend.headers.STSPreload: 'true'
           traefik.frontend.headers.frameDeny: 'true'
           traefik.frontend.auth.forward.address: '{{gauth}}'
           traefik.port: '{{intport3}}'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/pihole/{{pgrole}}:/etc/pihole'
          - '/opt/appdata/{{pgrole}}/dnsmasq.d:/etc/dnsmasq.d'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          ServerIP: '192.168.100.5'
          PROXY_LOCATION: '{{pgrole}}'
          VIRTUAL_HOST: '{{pgrole}}.{{domain.stdout}}'
          VIRTUAL_PORT: '{{intport3}}'
          TZ: '${TZ}'
          WEBPASSWORD: 'seximy'
          DNS1: '127.0.0.1'
          DNS2: '1.1.1.1'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
          - '{{ports.stdout}}{{extport2}}:{{intport2}}'
          - '{{ports.stdout}}{{extport3}}:{{intport3}}'
          - '{{ports.stdout}}{{extport4}}:{{intport4}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'
